query CartValidationsGenerateRunInput {
  buyerJourney {
    step
  }
  shop {
    localTime {
      isCampaignPeriod: dateTimeBetween(
        startDateTime: "2026-07-01T16:20:00"
        endDateTime: "2026-07-16T07:00:00"
      )
    }
    metaobject(
      handle: {
        type: "app--379210334209--gwp"
        handle: "app--379210334209--gwp-usymljaq"
      }
    ) {
      condition_type: field(key: "condition_type") {
        value
      }
    }
  }
  cart {
    buyerIdentity {
      customer {
        hasTags(tags: ["gwp-test"]) {
          hasTag
          tag
        }
      }
    }
    cost {
      totalAmount {
        amount
        currencyCode
      }
    }
    lines {
      quantity
      cost {
        totalAmount {
          amount
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          product {
            id
          }
        }
      }
    }
  }
}
